import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Righteous, Ysabeau_Office, Joan } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const righteous = Righteous({
  subsets: ["latin"],
  weight: ["400"],
});

const joan = Joan({
  subsets: ["latin"],
  weight: "400",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${righteous.className} ${joan.className}`}>
        {children}
      </body>
    </html>
  );
}
